### ISSUE TITLE
Build failed with "fatal: No names found, cannot describe anything."

### ISSUE THREAD

**Issue by dbouclier** [jimschubert/query-tag-action#7]
Hello, 
My build failed with the following error
![image](https://github.com/jimschubert/query-tag-action/assets/98832464/60224e86-16fd-4856-836a-6eabe9f34f12)

Here my configuration: 
```
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          commit-ish: HEAD
          abbrev: 6
```

I guess it's a normal situation on a newly created repository without any tags.

maybe I did something wrong in the setup ?
maybe this GitHub action can handle this case, for example in that specific case the exit code can be 0 and the output empty, what do you think?
